version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
  - cmd: dotnet restore
  - cmd: nuget restore

  test:
  # only assemblies to test
  assemblies:
    only:
      - '**\*.UnitTests.dll'